image: docker:stable


variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

services:
  - name: docker:dind
    command: ["--insecure-registry=git.ropod.org:4567"] # self-signed cetificate

stages:
  - build
  - test
  - release

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.ropod.org:4567

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
test:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE bash -c "cd /opt/ropod/ropod_common/ropodcpp/zyre_communicator/ && mkdir build && cd build && cmake .. && make"

release-stable-image:
  variables:
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:stable
    DOCKERHUB_RELEASE_IMAGE: ropod/ropod_common
  stage: release
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $DOCKERHUB_RELEASE_IMAGE
    - docker push $DOCKERHUB_CONTAINER_RELEASE_IMAGE
  only:
    - master
    - tags

release-latest-image:
  stage: release
  variables:
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
    DOCKERHUB_RELEASE_IMAGE: ropod/ropod_common
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $DOCKERHUB_RELEASE_IMAGE
    - docker push $DOCKERHUB_CONTAINER_RELEASE_IMAGE
  only:
    - develop
